#include "Msg_VhallRightExtraWidget.h"
STRU_VHALLRIGHTEXTRAWIDGET_INIT_USERINFO::STRU_VHALLRIGHTEXTRAWIDGET_INIT_USERINFO(){
   memset(this, 0, sizeof(STRU_VHALLRIGHTEXTRAWIDGET_INIT_USERINFO));
}
STRU_VHALLRIGHTEXTRAWIDGET_COMMONINFO::STRU_VHALLRIGHTEXTRAWIDGET_COMMONINFO() {
   memset(this, 0, sizeof(STRU_VHALLRIGHTEXTRAWIDGET_COMMONINFO));
	bStartInteraction = true;
}
