#include "Msg_OBSControl.h"


STRU_OBSCONTROL_PUBLISH::STRU_OBSCONTROL_PUBLISH() {
   memset(this, 0, sizeof(STRU_OBSCONTROL_PUBLISH));
   m_iQuality = -1;
   m_bIsSaveFile = false;
   m_bMediaCoreReConnect = false;
}


STRU_OBSCONTROL_WINDOWSRC::STRU_OBSCONTROL_WINDOWSRC() {
   memset(this, 0, sizeof(STRU_OBSCONTROL_WINDOWSRC));
}

STRU_OBSCONTROL_SHAREREGION::STRU_OBSCONTROL_SHAREREGION() {
   memset(this, 0, sizeof(STRU_OBSCONTROL_SHAREREGION));
}

STRU_OBSCONTROL_PROCESSSRC::STRU_OBSCONTROL_PROCESSSRC() {
   memset(this, 0, sizeof(STRU_OBSCONTROL_PROCESSSRC));
}

STRU_OBSCONTROL_AUDIO_CAPTURE::STRU_OBSCONTROL_AUDIO_CAPTURE() {
   memset(this, 0, sizeof(STRU_OBSCONTROL_AUDIO_CAPTURE));
}

STRU_OBSCONTROL_VIDIO_SET::STRU_OBSCONTROL_VIDIO_SET()
{
	memset(this, 0, sizeof(STRU_OBSCONTROL_VIDIO_SET));
}

PLUGIN_DATA::PLUGIN_DATA() {
   data = NULL;
   length = 0;
}
